#!/usr/bin/env node
/**
 * Vendors render-time assets into `vendor/` so compositions are fully
 * self-contained.
 *
 * Two reasons this exists rather than linking a CDN:
 *   1. Determinism. A composition that fetches fonts at render time can
 *      render early frames in a fallback face if the network is slow,
 *      which shows up as a visible "pop" mid-video.
 *   2. Sandboxes. Headless Chromium frequently has no egress even when
 *      the host does, so CDN links silently break the render.
 *
 * Fonts are inlined as base64 woff2 inside a single stylesheet, so the
 * composition needs exactly two local files.
 *
 *   node tools/vendor-assets.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "..");
const vendorDir = path.join(projectRoot, "vendor");
fs.mkdirSync(vendorDir, { recursive: true });

const require = (await import("node:module")).createRequire(import.meta.url);

/* ---------------- GSAP ---------------- */
const gsapSrc = require.resolve("gsap/dist/gsap.min.js");
fs.copyFileSync(gsapSrc, path.join(vendorDir, "gsap.min.js"));
console.log("vendored gsap.min.js");

/* ---------------- fonts ---------------- */
// family -> [fontsource package, weights, css family name, style]
const FAMILIES = [
  ["@fontsource/archivo-black", [400], "Archivo Black"],
  ["@fontsource/caveat", [600, 700], "Caveat"],
  ["@fontsource/patrick-hand", [400], "Patrick Hand"],
  ["@fontsource/roboto-mono", [500], "Roboto Mono"],
];

let css = `/* Generated by tools/vendor-assets.mjs — do not edit by hand. */\n`;

for (const [pkg, weights, family] of FAMILIES) {
  const pkgDir = path.dirname(require.resolve(`${pkg}/package.json`));
  for (const weight of weights) {
    // fontsource ships files as files/<name>-<subset>-<weight>-<style>.woff2
    const filesDir = path.join(pkgDir, "files");
    const candidates = fs
      .readdirSync(filesDir)
      .filter(
        (f) =>
          f.endsWith(".woff2") &&
          f.includes("-latin-") &&
          f.includes(`-${weight}-`) &&
          f.includes("-normal")
      );
    if (!candidates.length) {
      console.warn(`  ! no latin woff2 for ${family} ${weight}`);
      continue;
    }
    const b64 = fs.readFileSync(path.join(filesDir, candidates[0])).toString("base64");
    css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64}) format("woff2");}\n`;
    console.log(`vendored ${family} ${weight} (${Math.round(b64.length / 1365)}KB)`);
  }
}

fs.writeFileSync(path.join(vendorDir, "brand-fonts.css"), css);
console.log(`wrote vendor/brand-fonts.css`);
